[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pyAS4"
version = "8"
description = "Your package description"
authors = [{ name="Andrey Shapovalov" }]
readme = "README.md"
requires-python = ">=3.10"
dependencies = []